os: linux

language: r
r:
  - release
  - devel

cache: packages

before_install:
  - tlmgr install standalone showexpl imakeidx xpatch

apt_packages:
  - libxml2-dev

script:
- R CMD build .
- R CMD check *tar.gz
