os: linux

apt_packages:
  - libxml2-dev

addons:
  apt:
    update: true
    packages:
      - libgs-dev
      - qpdf
      - ghostscript

language: r

r:
  - release
  - devel
  - oldrel

env:
  - PKG_TARBALL=pdynmc_0.8.0.tar.gz

sudo: required

before_install:
  - tlmgr install index

cache:
 - packages
 - apt: true
pandoc_version: 1.19.2.1
r_github_packages:
  - r-lib/covr
  - r-lib/pkgdown

warnings_are_errors: true

services: docker

script:
  - docker pull dxjoke/tectonic-docker
  - docker run --mount src=$TRAVIS_BUILD_DIR/src,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic main.tex"
  - R CMD build . --compact-vignettes=gs+qpdf
  - R CMD check *tar.gz --as-cran


notifications:
  email: false
