os: linux

language: r

warnings_are_errors: true

sudo: false

global:
  - R_BUILD_ARGS=--no-manual
  - R_CHECK_ARGS=--no-manual --as-cran

services: docker

script:
  - docker pull dxjoke/tectonic-docker
  - R CMD check . --as-cran

notifications:
  email: false
