language: r

warnings_are_errors: true

sudo: required

before_install:
  - tlmgr install amsmath amssymb nicefrac arydshln

install: echo Installation step #do not remove this line!

notifications:
  email: false
