language: r
r:
  - release
  - devel

warnings_are_errors: true

cache: packages

os: linux

sudo: required

services: docker


script:
  - docker pull dxjoke/tectonic-docker
  - R CMD build . --compact-vignettes=gs+qpdf
  - R CMD check *tar.gz --as-cran

addons:
  apt:
    update: true
    packages:
      - libgs-dev
      - qpdf
      - ghostscript




# deploy to github
deploy:
  provider: releases
  cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  file: pdynmc*.t*gz
  on:
    tags: true
    repo: markusfritsch/pdynmc
