language: r
r:
  - release
  - devel

warnings_are_errors: true

cache: packages

os: linux

services: docker


script:
  - docker pull dxjoke/tectonic-docker
  - R CMD build .
  - R CMD check pdynmc_0.8.0.tar.gz --as-cran




## deploy to github
#deploy:
#  provider: releases
#  cleanup: true
#  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#  keep_history: true
#  file: pdynmc*.t*gz
#  on:
#    branch: master
#    tags: true
#    repo: markusfritsch/pdynmc
