language: r
  - oldrel
  - release
  - devel

warnings_are_errors: true

services: docker

script:
  - docker pull dxjoke/tectonic-docker
  - R CMD check *tar.gz --as-cran

notifications:
  email: false
