language: r
r:
  - oldrel
  - release
  - devel

#r_github_packages:
#  - r-lib/pkgdown

env:
    - PKG_TARBALL=pdynmc_0.9.1.tar.gz

#warnings_are_errors: true

#cache:
#  packages
#  directories:
#    - $HOME/.cache/Tectonic

#define operating system
os: linux


## required to rebuild vignette when building the package
#before_install:
#  # Download and install conda
#  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
#  - bash $HOME/miniconda.sh -b -u -p $HOME/miniconda
#  - export PATH="$HOME/miniconda/bin:$PATH"
#  - hash -r
#    # Install tectonic
#  - conda install -y -c conda-forge tectonic==0.1.12


services: docker

script:
  - docker pull dxjoke/tectonic-docker
#  - docker run --mount src=$TRAVIS_BUILD_DIR/src,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic main.tex"
  - R CMD build . --no-build-vignettes
#  - R CMD build . --compact-vignettes=gs+qpdf
  - R CMD check *tar.gz --as-cran --no-build-vignettes
  - travis_wait 60 R CMD check *tar.gz --as-cran --no-build-vignettes


addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - qpdf
      - ghostscript



#r_github_packages:
#  - r-lib/pkgdown
#
#
#after_success:
#      - tar -C .. -xf $PKG_TARBALL
#      - rm -rf pdynmc.Rcheck
#      - Rscript -e 'pkgdown::build_site()'
#
#before_deploy:
#      # Set up git user name and tag this commit
#      - git config --local user.name markusfritsch
#      - git config --local user.email markus.fritsch@uni-passau.de
#      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#      - git tag $TRAVIS_TAG
#
#deploy:
#  provider: releases
#  api_key:
#    secure: $GITHUB_TOKEN
#  file_glob: true
#  file: pdynmc*.t*gz
#  skip_cleanup: true
#  overwrite: true
#  on:
#    tags: true
#    repo: markusfritsch/pdynmc



## required to deploy to github
#---
# the following github-repo may help:
# https://github.com/zappingseb/RTest/blob/master/.travis.yml
