os: linux

apt_packages:
  - libxml2-dev

language: r

r:
  - release

r_check_args: --as-cran --no-build-vignettes

warnings_are_errors: true

services: docker

script:
  - docker pull dxjoke/tectonic-docker
  - R CMD check pdynmc_0.8.0.tar.gz --as-cran

notifications:
  email: false
