os: linux

language: r
r:
 -oldrel
 -release
 -devel

warnings_are_errors: true

sudo: required

services: docker

script:
  - docker pull dxjoke/tectonic-docker
  - R CMD check . --as-cran

notifications:
  email: false
