os: linux

language: r
r:
  - release
  - devel

cache: packages

sudo apt-get install texlive-latex-extra --no-install-recommends

apt_packages:
  - libxml2-dev

script:
- R CMD build .
- R CMD check *tar.gz
