language: r
r:
  - release
  - devel

os: linux

cache:
  directories:
    - $HOME/.cache/Tectonic

sudo: required

before_install:
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true

services: docker

apt_packages:
  - libxml2-dev

script:
  - docker pull dxjoke/tectonic-docker
  - docker run --mount src=$TRAVIS_BUILD_DIR/src,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic main.tex"
  - R CMD build . --compact-vignettes=gs+qpdf
  - R CMD check *tar.gz --as-cran

addons:
  apt:
    update: true
    packages:
      - libgs-dev
      - qpdf
      - ghostscript




# deploy to github
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  repo: markusfritsch/pdynmc
  on:
    branch: master
