language: r
r:
  - release
  - devel

r_github_packages:
  - r-lib/pkgdown

env:
    - PKG_TARBALL=pdynmc_0.9.1.tar.gz

warnings_are_errors: true

cache:
  packages
#  directories:
#    - $HOME/.cache/Tectonic

#define operating system
os: linux


## required to rebuild vignette when building the package
#before_install:
#  # Download and install conda
#  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
#  - bash $HOME/miniconda.sh -b -u -p $HOME/miniconda
#  - export PATH="$HOME/miniconda/bin:$PATH"
#  - hash -r
#    # Install tectonic
#  - conda install -y -c conda-forge tectonic==0.1.12


services: docker


script:
  - docker pull dxjoke/tectonic-docker
#  - R CMD build . --no-build-vignettes
  - R CMD build . --compact-vignettes=gs+qpdf
  - travis_wait 40 R CMD check pdynmc_0.9.1.tar.gz --as-cran --no-build-vignettes




after_success:
      - tar -C .. -xf $PKG_TARBALL
      - rm -rf pdynmc.Rcheck
      - Rscript -e 'pkgdown::build_site()'

deploy:
  - provider: releases
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        file: $PKG_TARBALL
        on:
          tags: true
  - provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep-history: true
        local-dir: docs
        on:
          branch: master



## required to deploy to github
#---
# the following github-repo may help:
# https://github.com/zappingseb/RTest/blob/master/.travis.yml
