os: linux

language: r
r:
  - release
  - devel

cache:
  directories:
    - $HOME/.cache/Tectonic

sudo: required

services: docker

apt_packages:
  - libxml2-dev

script:
  - docker pull dxjoke/tectonic-docker
  - R CMD build .
  - R CMD check *tar.gz
