os: linux

language: r

r:
  - release
  - devel
  - oldrel

sudo: required

warnings_are_errors: true

services: docker

script:
  - docker pull dxjoke/tectonic-docker
  - R CMD check --as-cran

notifications:
  email: false
